#!/usr/bin/env bash
set -e
[ -n "$EXENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  echo "usage: exenv completions COMMAND [arg1 arg2...]" >&2
  exit 1
fi

COMMAND_PATH="$(command -v "exenv-$COMMAND" || command -v "exenv-sh-$COMMAND")"
if grep -i "^# provide exenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
