#!/usr/bin/env bash
set -e
[ -n "$EXENV_DEBUG" ] && set -x

root="$EXENV_DIR"
while [ -n "$root" ]; do
  if [ -e "${root}/.exenv-version" ]; then
    echo "${root}/.exenv-version"
    exit
  fi
  root="${root%/*}"
done

global_version_file="${EXENV_ROOT}/version"

if [ -e "$global_version_file" ]; then
  echo "$global_version_file"
elif [ -e "${EXENV_ROOT}/global" ]; then
  echo "${EXENV_ROOT}/global"
elif [ -e "${EXENV_ROOT}/default" ]; then
  echo "${EXENV_ROOT}/default"
else
  echo "$global_version_file"
fi
