#!/usr/bin/env bash
set -e
[ -n "$EXENV_DEBUG" ] && set -x

# Provide exenv completions
if [ "$1" = "--complete" ]; then
  echo exec
  echo rehash
  echo which
  exit
fi

EXENV_COMMAND="$1"
if [ -z "$EXENV_COMMAND" ]; then
  echo "usage: exenv hooks COMMAND" >&2
  exit 1
fi

resolve_link() {
  $(type -p greadlink readlink | head -1) $1
}

realpath() {
  local cwd="$(pwd)"
  local base="$(basename $1)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  echo "$(pwd)/$base"
  cd "$cwd"
}

shopt -s nullglob
for path in ${EXENV_HOOK_PATH//:/$'\n'}; do
  for script in $path/"$EXENV_COMMAND"/*.bash; do
    echo $(realpath $script)
  done
done
shopt -u nullglob
