#!/usr/bin/env bash
set -e
[ -n "$EXENV_DEBUG" ] && set -x

print=""
no_rehash=""
for args in "$@"
do
  if [ "$args" = "-" ]; then
    print=1
		shift
  fi

  if [ "$args" = "--no-rehash" ]; then
    no_rehash=1
    shift
  fi
done


if [ -z "$shell" ]; then
  shell="$(basename "$SHELL")"
fi

resolve_link() {
  $(type -p greadlink readlink | head -1) $1
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

root="$(abs_dirname "$0")/.."

if [ -z "$print" ]; then
  case "$shell" in
  bash )
    profile='~/.bash_profile'
    ;;
  zsh )
    profile='~/.zshrc'
    ;;
  ksh )
    profile='~/.profile'
    ;;
  fish )
    profile='~/.config/fish/config.fish'
    ;;
  * )
    profile='your profile'
    ;;
  esac

  { echo "# Load exenv automatically by adding"
    echo "# the following to ${profile}:"
    echo
    case "$shell" in
    fish )
      echo 'status --is-interactive; and . (exenv init -|psub)'
      ;;
    * )
      echo 'eval "$(exenv init -)"'
      ;;
    esac
    echo
  } >&2

  exit 1
fi

mkdir -p "${EXENV_ROOT}/"{shims,versions}

case "$shell" in
fish )
  echo "setenv PATH '${EXENV_ROOT}/shims' \$PATH"
  echo ". \"$root/completions/exenv.${shell}\""
  ;;
bash | zsh )
  echo 'export PATH="'${EXENV_ROOT}'/shims:${PATH}"'
  echo "source \"$root/completions/exenv.${shell}\""
  ;;
esac

if [ -z "$no_rehash" ]; then
  echo 'exenv rehash 2>/dev/null'
fi

commands=(`exenv commands --sh`)
case "$shell" in
fish )
  cat <<EOS
function exenv
  set command \$argv[1]
  set -e argv[1]

  switch "\$command"
  case ${commands[*]}
    eval (exenv "sh-\$command" \$argv)
  case '*'
    command exenv "\$command" \$argv
  end
end
EOS
  ;;
* )
  ;;
esac

if [ "$shell" != "fish" ]; then
IFS="|"
cat <<EOS
exenv() {
  local command="\$1"
  if [ "\$#" -gt 0 ]; then
    shift
  fi

  case "\$command" in
  ${commands[*]})
    eval \`exenv "sh-\$command" "\$@"\`;;
  *)
    command exenv "\$command" "\$@";;
  esac
}
EOS
fi
