#!/usr/bin/env bash
set -e
[ -n "$EXENV_DEBUG" ] && set -x

# Provide exenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec exenv-versions --bare
fi

EXENV_VERSION="$1"
EXENV_VERSION_FILE="${EXENV_ROOT}/version"

if [ -n "$EXENV_VERSION" ]; then
  exenv-version-file-write "$EXENV_VERSION_FILE" "$EXENV_VERSION"
else
  exenv-version-file-read "$EXENV_VERSION_FILE" ||
  exenv-version-file-read "${EXENV_ROOT}/global" ||
  exenv-version-file-read "${EXENV_ROOT}/default" ||
  echo system
fi
